import { rename, rm } from "node:fs/promises";
import { basename, dirname, join, relative, sep } from "node:path";
import type { C2paRecord } from "@video-studio/schema";
import { type CommandRunner, defaultRunner, which } from "@video-studio/voice";

/**
 * C2PA content credentials for exported videos (Phase 8, opt-in: `export {sign: true}`).
 *
 * Signing uses the local `c2patool` (never bundled, never installed by the plugin). Without a
 * signer configured in c2patool's settings (`C2PATOOL_SETTINGS` or `~/.config/c2pa/c2pa.toml`)
 * c2patool signs with its built-in test certificate ("C2PA Test Signing Cert"): the manifest is
 * well-formed and its hashes validate, but validators report `signingCredential.untrusted`.
 * The record says which one was used (`certificate: "test" | "user"`).
 *
 * The manifest holds:
 * - `c2pa.actions`: one `c2pa.created` action with softwareAgent video-studio/<engine version>
 *   and an IPTC `digitalSourceType` (see {@link classifySource});
 * - `stds.schema-org.CreativeWork` with the video's title.
 * c2patool adds the hard binding (`c2pa.hash.bmff`) and records the unsigned file as parent
 * ingredient.
 */

export const IPTC_DST = "http://cv.iptc.org/newscodes/digitalsourcetype/";
export const DST_TRAINED = `${IPTC_DST}trainedAlgorithmicMedia`;
export const DST_COMPOSITE_TRAINED = `${IPTC_DST}compositeWithTrainedAlgorithmicMedia`;
export const DST_DIGITAL_CREATION = `${IPTC_DST}digitalCreation`;

export const C2PA_ASSERTIONS = ["c2pa.actions", "stds.schema-org.CreativeWork"] as const;

/** Scene renderers that draw locally and deterministically (no trained model). */
const LOCAL_RENDERER_PREFIXES = ["hyperframes", "ffmpeg", "remotion"];
/** Voice backends that produce no synthetic speech. */
const NO_SYNTHETIC_VOICE = new Set(["silent", "native", "none"]);

export interface SourceFacts {
  /** Voice backend id (silent, system, elevenlabs, …). */
  voice_backend: string;
  /** Whether the voice track has audio (silent renders have none). */
  voice_has_audio: boolean;
  /** One entry per scene. */
  scenes: Array<{ renderer: string; placeholder?: boolean }>;
}

export interface SourceClass {
  digital_source_type: string;
  ai_generated: boolean;
  reasons: string[];
}

/**
 * Pick the IPTC digital source type, conservatively (when in doubt, disclose):
 * - every scene generated by a model (a non-local renderer) and no local graphics:
 *   `trainedAlgorithmicMedia`;
 * - any model-made part (generated scenes, or any synthesized voice, including the system TTS,
 *   because current system voices are neural models): `compositeWithTrainedAlgorithmicMedia`;
 * - only local motion graphics, footage the user supplied, and no synthetic voice:
 *   `digitalCreation`.
 * `ai_generated` is true for the first two.
 */
export function classifySource(f: SourceFacts): SourceClass {
  const reasons: string[] = [];
  const generated = f.scenes.filter((s) => !s.placeholder && !LOCAL_RENDERER_PREFIXES.some((p) => s.renderer.startsWith(p)));
  const syntheticVoice = f.voice_has_audio && !NO_SYNTHETIC_VOICE.has(f.voice_backend);
  if (generated.length) reasons.push(`${generated.length} scene(s) generated by ${[...new Set(generated.map((s) => s.renderer))].join(", ")}`);
  if (syntheticVoice) reasons.push(`synthetic voice (${f.voice_backend} text-to-speech)`);
  if (generated.length && generated.length === f.scenes.length && (syntheticVoice || !f.voice_has_audio)) {
    return { digital_source_type: DST_TRAINED, ai_generated: true, reasons };
  }
  if (generated.length || syntheticVoice) {
    reasons.push("composited with local motion graphics");
    return { digital_source_type: DST_COMPOSITE_TRAINED, ai_generated: true, reasons };
  }
  reasons.push("local motion graphics and user-supplied media only; no synthetic voice");
  return { digital_source_type: DST_DIGITAL_CREATION, ai_generated: false, reasons };
}

export interface ManifestInput {
  title: string;
  engineVersion: string;
  digitalSourceType: string;
}

/** The manifest definition passed to c2patool (`-c`). */
export function c2paManifestDefinition(i: ManifestInput): Record<string, unknown> {
  return {
    claim_generator_info: [{ name: "video-studio", version: i.engineVersion }],
    title: i.title,
    assertions: [
      {
        label: "c2pa.actions",
        data: {
          actions: [
            {
              action: "c2pa.created",
              softwareAgent: { name: "video-studio", version: i.engineVersion },
              digitalSourceType: i.digitalSourceType,
            },
          ],
        },
      },
      {
        label: "stds.schema-org.CreativeWork",
        data: { "@context": "https://schema.org", "@type": "CreativeWork", name: i.title },
      },
    ],
  };
}

export interface C2paTool {
  path: string;
  version: string;
}

export interface C2paDeps {
  env?: Record<string, string | undefined>;
  runner?: CommandRunner;
}

/** Locate c2patool: `C2PATOOL_PATH`, then PATH. Null when absent or not runnable. */
export async function findC2patool(deps: C2paDeps = {}): Promise<C2paTool | null> {
  const env = deps.env ?? process.env;
  const run = deps.runner ?? defaultRunner;
  const path = env.C2PATOOL_PATH || which("c2patool", env);
  if (!path) return null;
  try {
    const r = await run(path, ["--version"]);
    if (r.code !== 0) return null;
    return { path, version: r.stdout.trim().replace(/^c2patool\s+/, "") || "unknown" };
  } catch {
    return null;
  }
}

/**
 * Sign `file` in place: c2patool writes a signed copy next to it, which then replaces it.
 * Returns which certificate signed it.
 */
export async function signFile(tool: C2paTool, file: string, definition: Record<string, unknown>, deps: C2paDeps = {}): Promise<{ certificate: "test" | "user" }> {
  const run = deps.runner ?? defaultRunner;
  const tmp = join(dirname(file), `.${basename(file, ".mp4")}.signing.mp4`);
  await rm(tmp, { force: true });
  try {
    const r = await run(tool.path, [file, "-c", JSON.stringify(definition), "-o", tmp, "-f"]);
    if (r.code !== 0) throw new Error((r.stderr || r.stdout).trim().split("\n").slice(-3).join(" ") || `exit ${r.code}`);
    await rename(tmp, file);
    return { certificate: /default private key|test signing cert/i.test(`${r.stdout}\n${r.stderr}`) ? "test" : "user" };
  } finally {
    await rm(tmp, { force: true });
  }
}

/** Read the C2PA manifest store of `file` (c2patool's JSON report), or null when it has none. */
export async function readC2pa(tool: C2paTool, file: string, deps: C2paDeps = {}): Promise<Record<string, unknown> | null> {
  const run = deps.runner ?? defaultRunner;
  const r = await run(tool.path, [file]);
  if (r.code !== 0) return null;
  const start = r.stdout.indexOf("{");
  if (start < 0) return null;
  try {
    return JSON.parse(r.stdout.slice(start)) as Record<string, unknown>;
  } catch {
    return null;
  }
}

export interface SignVideosInput extends C2paDeps {
  /** Project root: `signed` paths in the record are relative to it. */
  root: string;
  files: string[];
  title: string;
  engineVersion: string;
  facts: SourceFacts;
}

export interface SignVideosResult {
  record?: C2paRecord;
  /** Absolute paths of the files that now carry a manifest. */
  signed: string[];
  warnings: string[];
}

/**
 * Sign every file; a failure on one file is a warning (that file stays unsigned). Without
 * c2patool nothing is signed and the warning says how to get it; export still succeeds.
 */
export async function signVideos(i: SignVideosInput): Promise<SignVideosResult> {
  const warnings: string[] = [];
  const tool = await findC2patool(i);
  if (!tool) {
    return {
      signed: [],
      warnings: [
        "c2pa: c2patool not found (install it, e.g. `brew install c2patool` or `cargo install c2patool`, or set C2PATOOL_PATH); the videos were exported unsigned",
      ],
    };
  }
  const cls = classifySource(i.facts);
  const definition = c2paManifestDefinition({ title: i.title, engineVersion: i.engineVersion, digitalSourceType: cls.digital_source_type });
  const signed: string[] = [];
  const certs = new Set<"test" | "user">();
  for (const f of i.files) {
    try {
      const r = await signFile(tool, f, definition, i);
      certs.add(r.certificate);
      signed.push(f);
    } catch (e) {
      warnings.push(`c2pa: could not sign ${relative(i.root, f).split(sep).join("/")}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  if (!signed.length) return { signed, warnings };
  const certificate = certs.has("test") ? "test" : "user";
  if (certificate === "test") {
    warnings.push("c2pa: signed with c2patool's built-in test certificate; validators show the credentials as untrusted. Configure your own signer in c2patool's settings for trusted credentials");
  }
  return {
    signed,
    warnings,
    record: {
      tool: `c2patool ${tool.version}`,
      certificate,
      claim_generator: `video-studio/${i.engineVersion}`,
      assertions: [...C2PA_ASSERTIONS],
      signed: signed.map((f) => relative(i.root, f).split(sep).join("/")),
      ai_generated: cls.ai_generated,
    },
  };
}
